---
driver:
  name: vagrant
  vagrantfile_erb: Vagrantfile.erb

driver_config:
  customize:
    memory: 4096
  network:
    - - forwarded_port
      - guest: 9000
        host: 9000
        auto_correct: true
    - - forwarded_port
      - guest: 12201
        host: 12201
        auto_correct: true
    - - forwarded_port
      - guest: 12201
        host: 12201
        auto_correct: true
        protocol: udp

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 15
  install_strategy: once
  data_path: test

platforms:
- name: centos-8.3
  attributes:
    mongodb:
      reload_action: "restart"
- name: ubuntu-20.04
  run_list:
  - recipe[apt]
- name: debian-10.10
  run_list:
  - recipe[apt]

suites:
  - name: openjdk
    attributes:
      machine_fqdn: graylog.local
      machine_fqdn_as_hostname: true
      apt:
        compile_time_update: true
      java:
        jdk_version: '8'
        install_flavor: 'openjdk'
      mongodb:
        package_version: '4.2'
      graylog2:
        password_secret: "2jueVqZpwLLjaWxV"
        # Credentials are admin:admin
        root_password_sha2: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
        restart: "delayed"
        sidecar:
          release: '0.1.8'
          version: '0.1.8'
          build: 1
      elasticsearch:
        version: "7.10.2"
        cluster:
          name: "graylog"
    run_list:
      - recipe[fqdn]
      - recipe[curl]
      - recipe[sc-mongodb]
      - recipe[graylog2::java]
      - recipe[elasticsearch_test]
      - recipe[graylog2]
      - recipe[graylog2::server]
      - recipe[graylog2::collector_sidecar]
      - recipe[graylog2::authbind]
