AllCops:
  Exclude:
    - 'vendor/**/*'

AlignParameters:
  Enabled: false
ClassLength:
  Enabled: false
Documentation:
  Enabled: false
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Max: 30
Metrics/AbcSize:
  Enabled: false
SignalException:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/TrailingCommaInLiteral:
  Enabled: false
WordArray:
  Enabled: false
